<<<<<<< HEAD
cat <<EOF | kubectl apply -f -
=======
cat <<EOF > "${TEMP_SA}"
>>>>>>> karpenter-fix
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${KARPENTER_NAMESPACE}
  annotations:
<<<<<<< HEAD
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${KARPENTER_CONTROLLER_ROLE}
=======
    eks.amazonaws.com/role-arn: ${KARPENTER_CONTROLLER_ROLE}
>>>>>>> karpenter-fix
EOF
