cat <<EOF > "${TEMP_SA}"
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${KARPENTER_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: ${KARPENTER_CONTROLLER_ROLE}
EOF
