apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        workload-type: general
        managed-by: karpenter
    spec:
      nodeClassRef:
        name: default

      requirements:
        # Architecture
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        # OS
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        # Capacity type
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]

        # *** Only allow t3a instance types ***
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3a"]

  # Node lifecycle + consolidation
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
    budgets:
      - nodes: "10%"
        duration: 5m

  # Resource limits for this NodePool
  limits:
    cpu: "20"

  weight: 10
